# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Microsoft_Hackathon_1' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
	use_frameworks!

  # Pods for Microsoft_Hackathon_1
    pod 'PRAugmentedReality'
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'
    pod 'Firebase/Storage'
    pod 'SDWebImage'
	
  target 'Microsoft_Hackathon_1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Microsoft_Hackathon_1UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
